# Generated by Django 4.1.3 on 2022-11-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Please add alturnative text', max_length=255, null=True, verbose_name='Alturnative text'),
        ),
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(default='images/default.png', help_text='Upload a product image', upload_to='images/', verbose_name='image'),
        ),
    ]
