# Generated by Django 4.1.3 on 2022-11-19 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_university_alt_text_university_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название общежития')),
                ('date', models.PositiveSmallIntegerField(verbose_name='Год основания')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('link_address', models.TextField(verbose_name='Сслыка на адрес')),
                ('univers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_univers', to='university.university')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='stateandpaidinfo',
            name='paid_place',
            field=models.PositiveIntegerField(verbose_name='Сред. кол-во платных мест'),
        ),
        migrations.AlterField(
            model_name='stateandpaidinfo',
            name='paid_point',
            field=models.PositiveIntegerField(verbose_name='Средний балл плат. обучения'),
        ),
        migrations.AlterField(
            model_name='stateandpaidinfo',
            name='paid_price',
            field=models.PositiveIntegerField(verbose_name='Средняя стоимость плат. обучения'),
        ),
        migrations.AlterField(
            model_name='stateandpaidinfo',
            name='state_place',
            field=models.PositiveIntegerField(verbose_name='Сред. кол-во бюдж мест'),
        ),
        migrations.AlterField(
            model_name='stateandpaidinfo',
            name='state_point',
            field=models.PositiveIntegerField(verbose_name='Средний балл бюдж. обучения'),
        ),
        migrations.AlterField(
            model_name='stateandpaidinfo',
            name='state_price',
            field=models.PositiveIntegerField(verbose_name='Средняя стоимость бюдж. обучения'),
        ),
    ]
